# Generated by Django 2.2.6 on 2019-10-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=999999)),
                ('bank_name', models.CharField(max_length=999999)),
                ('bank_number', models.CharField(max_length=999999)),
                ('bank_date', models.CharField(max_length=999999)),
                ('bank_cvc', models.CharField(max_length=999999)),
                ('bank_added_time', models.CharField(max_length=999999)),
                ('bank_most_spent', models.CharField(max_length=999999)),
                ('bank_lest_spent', models.CharField(max_length=999999)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999999)),
                ('bio', models.CharField(max_length=999999)),
                ('img', models.CharField(max_length=999999)),
                ('tags', models.CharField(max_length=999999)),
                ('price', models.CharField(max_length=999999)),
                ('starts', models.CharField(max_length=999999)),
                ('sub_titles', models.CharField(max_length=999999)),
                ('videos', models.CharField(max_length=999999)),
                ('time_created', models.CharField(max_length=999999)),
                ('teacher', models.CharField(max_length=999999)),
                ('students', models.CharField(max_length=999999)),
                ('reviews', models.CharField(max_length=999999)),
                ('permission', models.CharField(max_length=999999)),
                ('best_raise_time', models.CharField(max_length=999999)),
                ('baddest_raise_time', models.CharField(max_length=999999)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=99999)),
                ('bio', models.CharField(max_length=99999)),
                ('time_added', models.CharField(max_length=99999)),
                ('user_img', models.CharField(max_length=99999)),
                ('status', models.CharField(max_length=99999)),
                ('views', models.CharField(max_length=99999)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999999)),
                ('username', models.CharField(max_length=999999)),
                ('bio', models.CharField(max_length=9999999)),
                ('email', models.CharField(max_length=999999)),
                ('password', models.CharField(max_length=999999)),
                ('profile_img', models.CharField(max_length=999999)),
                ('time_created', models.CharField(max_length=999999)),
                ('courses_made', models.CharField(max_length=999999)),
                ('amount_earned_total', models.CharField(max_length=999999)),
                ('amount_earned_last', models.CharField(max_length=999999)),
                ('amount_earned_first', models.CharField(max_length=999999)),
                ('bank_name', models.CharField(max_length=999999)),
                ('bank_number', models.CharField(max_length=999999)),
                ('most_course_ben', models.CharField(max_length=999999)),
                ('baddest_course_ben', models.CharField(max_length=999999)),
                ('middle_course_ben', models.CharField(max_length=999999)),
                ('last_money_took', models.CharField(max_length=999999)),
                ('first_money_took', models.CharField(max_length=999999)),
                ('students_got', models.CharField(max_length=999999)),
                ('best_course_students', models.CharField(max_length=999999)),
                ('baddest_course_students', models.CharField(max_length=999999)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999999)),
                ('username', models.CharField(max_length=999999)),
                ('bio', models.CharField(max_length=9999999)),
                ('email', models.CharField(max_length=999999)),
                ('password', models.CharField(max_length=999999)),
                ('profile_image', models.CharField(max_length=999999)),
                ('time_created', models.CharField(max_length=999999)),
                ('does_payed', models.CharField(max_length=999999)),
                ('courses_took', models.CharField(max_length=999999)),
                ('liked_courses', models.CharField(max_length=999999)),
                ('paying_times', models.CharField(max_length=999999)),
                ('total_times_payed', models.CharField(max_length=999999)),
                ('total_payed_money', models.CharField(max_length=999999)),
                ('last_pay_money', models.CharField(max_length=999999)),
                ('first_pay_money', models.CharField(max_length=999999)),
                ('bank_added_time', models.CharField(max_length=999999)),
                ('bank_name', models.CharField(max_length=999999)),
                ('bank_number', models.CharField(max_length=999999)),
                ('bank_cvc', models.CharField(max_length=999999)),
                ('bank_date', models.CharField(max_length=999999)),
                ('last_charge', models.CharField(max_length=999999)),
                ('wallet', models.CharField(max_length=999999)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999999)),
                ('bio', models.CharField(max_length=9999999)),
                ('course', models.CharField(max_length=999999)),
                ('sub_title', models.CharField(max_length=999999)),
                ('url', models.CharField(max_length=999999)),
                ('video_long_time', models.CharField(max_length=999999)),
                ('reviews', models.CharField(max_length=999999)),
                ('status', models.CharField(max_length=999999)),
            ],
        ),
    ]
