# Generated by Django 2.2.6 on 2019-10-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20191021_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=999999)),
                ('time_created', models.CharField(max_length=999999)),
                ('status', models.CharField(max_length=999999)),
                ('is_user', models.CharField(max_length=999999)),
            ],
        ),
    ]
