# Generated by Django 2.2.6 on 2019-10-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='bio',
            field=models.TextField(max_length=99999),
        ),
    ]
